inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rubocop_rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'spec/rubocop/fixtures/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 3.0

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'spec/fixtures/basic_rails_app/**/*'

Naming/FileName:
  Exclude:
   - 'lib/anycable-rails.rb'
