AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'lib/anycable/rpc/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'Gemfile'
    - 'Rakefile'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4

Rails:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/anycable-rails.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/rails/generators/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/rails/generators/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/rails/generators/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*.rb'
    - 'anycable-rails.gemspec'
    - 'lib/rails/generators/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/rails/generators/**/*.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/rails/generators/**/*.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/rails/generators/**/*.rb'

Lint/HandleExceptions:
  Enabled: false
