AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'bench/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'lib/anycable/rpc/**/*'
    - 'Rakefile'
    - 'Gemfile'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Style/AccessorMethodName:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals: 
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/PercentLiteralDelimeters:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'README.md'
    - 'CHANGELOG.md'
    - 'lib/anycable-rails.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false