test:
  rpc_host: "localhost:50123"
  websocket_url: "ws://local.test/cable"
  broadcast_adapter: http
  access_logs_disabled: false
  persistent_session_enabled: true
  http_rpc_mount_path: "/_anycable"
  batch_broadcasts: true
  jwt_secret: "jotz"
