version: '2.4'

services:
  app:
    image: ruby:2.6
    environment:
      - HISTFILE=/app/tmp/.bash_history
    working_dir: /app
    volumes:
      - ..:/app
      - gems:/usr/local/bundle

volumes:
  gems:
