#!/usr/bin/env ruby
# frozen_string_literal: true
require ::File.expand_path('../../config/environment', __FILE__)
require "anycable-rails"

Anycable.configure do |config|
  config.connection_factory = ActionCable.server.config.connection_class.call
end

Rails.application.eager_load!

Anycable::Server.start
